In [1]:
import numpy as np

In [2]:
narr = np.array([[1, 2, 3]])
narr

array([[1, 2, 3]])

In [3]:
np.resize(narr, (4, 4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [4]:
narr.resize((3, 3), refcheck=False)

In [5]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
matrix = np.ones((5, 4))
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
matrix = np.zeros((4, 4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.diag(narr)

array([1, 0, 0])

In [9]:
np.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [10]:
m1 = np.ones((4, 5), dtype=int)
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
m2 = np.zeros((4, 5), dtype=int)
m2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
np.vstack([m1, m2])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
np.hstack([m1, m2])

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [14]:
[1, 2, 3] * [4, 5, 5]

TypeError: can't multiply sequence by non-int of type 'list'

In [15]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 5])

In [16]:
z = x * y
z

array([ 4, 10, 15])

In [17]:
x ** 2

array([1, 4, 9])

In [18]:
x.dot(y)

29

In [19]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [20]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [21]:
narr.sum()

6

In [22]:
narr.max()

3

In [23]:
narr.min()

0

In [24]:
narr.argmax()

2

In [25]:
narr.argmin()

3

In [26]:
narr.mean()

0.6666666666666666

In [27]:
narr.std()

1.0540925533894598

In [28]:
mr = np.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [29]:
mr[-6:14:2]

array([ 81, 121, 169])

In [30]:
mr[5:-1:-1]

array([], dtype=int64)

In [31]:
mr[2]

4

In [32]:
mr[1:5]

array([ 1,  4,  9, 16])

In [33]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [34]:
mr[-2:]

array([169, 196])

In [35]:
mr[10::2]

array([100, 144, 196])

In [36]:
mr[-10:-2:2]

array([ 25,  49,  81, 121])