In [1]:
import numpy as np

In [2]:
tarr = np.random.randint(0, 10, (4, 3))
tarr

array([[9, 5, 3],
       [8, 9, 5],
       [9, 8, 9],
       [8, 0, 3]])

In [3]:
tarr[3::3, 4:1:-2]

array([[3]])

In [4]:
for r in tarr:
    r = r ** 2
    print(r)

[81 25  9]
[64 81 25]
[81 64 81]
[64  0  9]


In [5]:
for i, r in enumerate(tarr):
    print(f"index({str(i)}) is {r}")

index(0) is [9 5 3]
index(1) is [8 9 5]
index(2) is [9 8 9]
index(3) is [8 0 3]


In [6]:
narr = np.array([
    [1, 2, 3],
    [0, 0, 0],
    [2, 2, 1]
])
marr = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])

In [7]:
list(zip(narr, marr))

[(array([1, 2, 3]), array([0, 0, 0])),
 (array([0, 0, 0]), array([0, 0, 0])),
 (array([2, 2, 1]), array([0, 0, 0]))]

In [8]:
arr = [1, 4, 2, 9, 8, 6, 3]
arr = np.array(arr)
arr

array([1, 4, 2, 9, 8, 6, 3])

In [9]:
len(arr) // 2

3

In [10]:
p = arr[len(arr) // 2]
p

9

In [11]:
l = [x for x in arr if x > p]
l

[]

In [12]:
r = [x for x in arr if x < p]
r

[1, 4, 2, 8, 6, 3]

In [13]:
m = [x for x in arr if x == p]
m

[9]

In [14]:
l + m + r

[9, 1, 4, 2, 8, 6, 3]

In [15]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = np.array(arr)
    p = arr[len(arr) // 2]
    m = [x for x in arr if x == p]
    l = [x for x in arr if x < p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [16]:
h = [3, 6, 4, 1, 3, 9, 4]
quicksort(h)

[1, 3, 3, 4, 4, 6, 9]