In [1]:
import numpy as np

In [2]:
narr = np.array([
    [1, 2, 3],
    [0, 0, 0],
    [0, 0, 0],
])
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
narr[-2::1, 1:3]

array([[0, 0],
       [0, 0]])

In [4]:
narr[0:2, 1:3]

array([[2, 3],
       [0, 0]])

In [5]:
narr[::2, -1]

array([3, 0])

In [6]:
narr[::2, -1:]

array([[3],
       [0]])

In [7]:
narr[::-1, 2:]

array([[0],
       [0],
       [3]])

In [8]:
narr[narr >= 0]

array([1, 2, 3, 0, 0, 0, 0, 0, 0])

In [9]:
narr[narr >= 2]

array([2, 3])

In [10]:
narr >= 2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [11]:
marr = narr[-1]
marr

array([0, 0, 0])

In [12]:
marr[:] = 1
marr

array([1, 1, 1])

In [13]:
marr[:2] = 2
marr

array([2, 2, 1])

In [14]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [15]:
marr = narr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [16]:
marr[:] = 0

In [17]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])